# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Berd' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Berd
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Core'

  target 'BerdTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BerdUITests' do
    # Pods for testing
  end

end
